### ISSUE TITLE
Should we license this?

### ISSUE THREAD

**Issue by zmoazeni** [our-stories/west-marches#1]
I considered adding [cc-by-4.0](https://choosealicense.com/licenses/cc-by-4.0/). That seems somewhat appropriate for the content we'll be adding. I don't want it all to stay only under copyright.

Thoughts?

**Comment by zmoazeni** [comment]
I want to come back to this. I know it can sound silly to talk about licensing, but I think it would be a good idea to just make all of the content on here explicitly sharable. I think that's why Creative Commons Attribution 4.0 International makes the most sense above.

**Comment by crimsonknave** [comment]
Here's write up I found that talks about the licensing that Wizards allows for 5e content. https://medium.com/@MonsterCards/publishing-your-own-d-d-5th-edition-content-9b771f8b37d0

My understanding is that unless we were going to create just a setting and not actually tie it to anything 5e or the 5e rules we would need to use the OGL or DM's Guild. The OGL allows you to use everything in the SRD, but that can be fairly limited (for example, there is only a single rogue archetype). The DM's Guild allows you to use everything, but only if you are set in a few specific settings, you cannot use it for your own setting.

I'm no lawyer, so there may be considerations if we aren't charging for it, but I believe that we'll run into trademark type issues around some terms that Wizards is very finicky about such as `D&D`, `mind flayer` or basically any unique spell name.

**Comment by zmoazeni** [comment]
Oooh. That's interesting! Hrm. I need to think on that. Thanks!

**Comment by zmoazeni** [comment]
@crimsonknave I read through the link you posted as well as several others. This one was really good: https://dnd.wizards.com/articles/features/systems-reference-document-srd

Reading through the entirety in https://media.wizards.com/2016/downloads/DND/SRD-OGL_V5.1.pdf I think OGL fits us well. However we will have to keep an eye out for any reserved terms and update them. I think I can monitor it for now and even setup a GitHub Action to keep us audited and on our toes. I'm going to move forward with OGL for now.
