### ISSUE TITLE
Get the first session started

### ISSUE THREAD

**Issue by zmoazeni** [our-stories/west-marches#11]
Ideally I want players to drive this, but I have no problem driving the first couple sessions.

**Comment by crimsonknave** [comment]
I think it could be fun to have a few world building sessions where we discuss #12, decide some stuff, ship it and then iterate. Might help folks get to know each other and could also be short (30 minutes and up I'd think).

**Comment by zmoazeni** [comment]
@crimsonknave Yeah I'm good with that. I've been trying to avoid needing to have a Session 0 and set this up in a way we can sort it all out via GitHub async, but perhaps that's something to not avoid to at least get the ball rolling. Let me think on that. I may want to knock out a few things in a PR before then.

**Comment by zmoazeni** [comment]
Done with #34!
