### ISSUE TITLE
Character: Leowarin Hersandoral of Liaharice by the Sea

### ISSUE THREAD

**Issue by crimsonknave** [our-stories/west-marches#2]
_Please fill out your character as much as possible. Feel free to edit as much as you need. When you are all set, assign @zmoazeni to the issue._

**Name:** Leowarin Hersandoral of Liaharice by the Sea

If you need help with generating a name: https://www.fantasynamegenerators.com/dungeons-and-dragons.php

**Class** Rogue

**Background:** Courtier

**Race:** High Elf

**Alignment:** Chaotic Neutral

## Appearance:

**Age:**

**Height:**

**Weight:**

**Eyes:**

**Skin:**

**Hair:**

Description of the character that others would notice if they met them. Distinguishing tattoos, markings, mannerisms, voice.

Flesh this out as much as you can. This won't be set in stone.

## Backstory

Details TBD
* Minor High Elf Noble
* Got tired of being a nobody in Court and moved away to a new city
* Tries to pass off as somebody that's important
* Has an obsession with "Fine Art" and doesn't believe that others appreciate it as much as he does
  * So, he steals it and keeps it in a private museum where it can be appropriately appreciated
* Employs #3 as his personal Valet
* Doesn't like to leave civilized areas much, typically send Kravlok out for those things when needed
* Will also send Kravlok away when he's going to engage in something illegal

This is the Wooster part of my "Jeeves and Wooster" concept.

## Notes
I have mapped out the character at level 5 to get a feel for what they'll be like when they're more well rounded: https://www.dndbeyond.com/characters/32446917

## Abilities

**Strength:**

**Dexterity:**

**Constitution:**

**Intelligence:**

**Wisdom:**

**Charisma:**

## Skills

**Acrobatics (Dex):**

**Animal Handling (Wis):**

**Arcana (Int):**

**Athletics (Str):**

**Deception (Cha):**

**History (Int):**

**Insight (Wis):**

**Intimidation (Cha):**

**Investigation (Int):**

**Medicine (Wis):**

**Nature (Int):**

**Perception (Wis):**

**Performance (Cha):**

**Persuasion (Cha):**

**Religion (Int):**

**Sleight of Hand (Dex):**

**Stealth (Dex):**

**Survival (Wis):**

**Passive Wisdom (Perception):**

**Proficiency Bonus (Lv. 10):**

**Spell Attack Bonus:**

## Saving Throws

**Strength:**

**Dexterity:**

**Constitution:**

**Intelligence:**

**Wisdom:**

**Charisma:**

## Equipment and Spells

Armor, weapons, tools, known spells etc.

**Comment by zmoazeni** [comment]
@crimsonknave Hahah this is hilarious. So how will this play out? Are you wanting to RP two characters in a game?

I have no problems with the characters or even that they're level 5. We will have to figure that out when it comes to setting up a session.

**Comment by crimsonknave** [comment]
I see a few ways this can go.
* I play both characters. They may both be in a given session, but only one of them would be 'active' and the other would just be there for dialog. This would most commonly be me playing Kravlok and causing trouble as Leowarin.
* Someone likes the idea of playing either concept plays them and I play the other. This is actually my preferred option. I'd love to work with someone to make the characters fit together and the two could easily be :100: reworked to be different classes, races and so on.
* There is a running joke that they're never actually seen together despite their close relationship. They're both played by me, but I only play one at a time.
* One of them is a pure NPC and the other character just has a very strong bond to that NPC. The NPC would most likely be Leowarin as it seems to me that it would be weird to have a NPC butler for your adventurer, but being an adventuring butler for a trying elven noble would be fun.

All the characters I mock up are level 5 as that lets me get into the 'meat' of the character and see what they can become. I'm happy to play them starting at any level depending on where we want to start.

**Comment by crimsonknave** [comment]
Closing for now as I plan on playing Quay. Will open a new issue if want to play a different character.
