### ISSUE TITLE
Character: Karris (Apparent1#4498)

### ISSUE THREAD

**Issue by djigneo** [our-stories/west-marches#23]
_Please fill out your character as much as possible. Feel free to edit as much as you need. When you are all set, assign @zmoazeni to the issue._

**Name:** Karris ♀

* Race (and subraces if any): Githzerai
* Class(es) w/Levels: **Cleric** (Zeal)
* Alignment: CN / CG

**Character sheet:**

https://ddb.ac/characters/33406914/YxLwFU

## Appearance:
Comes off as haughty. Generally confident of her own abilities, but sometimes doubts she'll find her way back home.

**Age:** 23

**Height:** 5'5"

**Weight:** 125

**Eyes:** Gray

**Skin:** Pale yellow

**Hair:** Black, braided braids

## Backstory

Destined to become high priestess of _cult-like faction affiliated with fire, war, vengeance, blood._ Native to another plane of existence (Limbo or wherever) and was raised not wanting for much. Got used to the luxuries of life and is fairly knowedgeable about their home plane. Trained in the arts of magic, war, art, music. The faction was attacked and during the attack she was banished to another plane of existence - the material. Now she's trapped on the material plane, not knowing the outcome of the battle. Here no one knows her or how great she is and she doesn't know much about the world, other than the underlying mechanics of magic and war.

## Potential Plot Hooks

She is searching for magical knowledge and willing to take risks to find it. Wants to acquire magical secrets to find a way back to their home plane. Knows they won't find it by just sitting around so wants to explore and become powerful enough to find their way back, and if necessary, crush the enemies of her faction.

**Comment by zmoazeni** [comment]
I'm loving it @djigneo! One potential hook is that there are magical reagents known only to their area. And lots more undiscovered due to the Wilderness threat over the centuries. 

We live in an ancient land. And there are no doubt buried civilizations with their caches of treasure. Magical included.

I think I'm just going to go with Tal'Dorei from Critical Role. It avoids any sort of licensing issues with FR, and I can still homebrew within it. So if you like, take a look at some of the [Tal'Dorei Gods](https://taldorei-indy-dd-campaign.fandom.com/wiki/Tal%27Dorei_Gods).

**Comment by djigneo** [comment]
The deity that seems to fit from that list is The Stormlord. Yeah, I figure it's a concept that would give me as a player motivation to world-build and drive sessions - because the character wants to know something or acquire something.

**Comment by zmoazeni** [comment]
@djigneo can you push this information to the Wiki? I know I need a template. Don't push all the stats, attributes, etc to it. We can close this out once that's done!

**Comment by djigneo** [comment]
https://github.com/our-stories/west-marches/wiki/Character:-Karris,-the-Namer
@zmoazeni
