### ISSUE TITLE
Character: Amberscale

### ISSUE THREAD

**Issue by chrisbloom7** [our-stories/west-marches#31]
**Name:** Amberscale (If he has a clan name, it is known to few)

* Race (and subraces if any): Dragonborn
* Class(es) w/Levels: Sorcerer 3
* Alignment: Chaotic Good

**Character sheet:**

- https://www.dndbeyond.com/profile/chrisbloom7/characters/33376899
- https://www.dndbeyond.com/sheet-pdfs/chrisbloom7_33376899.pdf

## Appearance:

Amberscale's sleek draconian figure is mostly obscured beneath dark colored flowing hoodless robes. Cuffed sleeves reveal braceleted wrists and clean hands and nails. Well organized satchels and pouches hang from his shoulders and waist, within which one would find carefully maintained equipment, dutifully polished and oiled. Though not impatient, he suffers no halfwits - anyone who lacks the ability to see their own foolishness is not worthy of his time, time better spent studying, trading information, or otherwise advancing his interests. He is boastful but does not exaggerate, intelligent yet relatable. He is outgoing and generally boisterous, especially when he knows he has an audience and can show off his mental prowess. He is not cruel, but few would call him kind. Any generosity he shows is rarely from altruism.

**Age:** 25

**Height:** 6' 4"
 
**Weight:** 265

**Eyes:** Icy blue

**Skin:** Brassy red scales with flecks of gold

**Hair:** N/A

## Backstory

Amberscale was raised in a small clan who boasted a heritage that few other clans recognized. Still, it's members were proud and their bond was strong. His brood mothers encouraged his curiosity, and from an early age he loved to explore the dank cellars of his clan in search of forgotten heirlooms, heraldry, and history. By the time he exhausted those troves he was old enough to gain admission to the clan's knowledge halls and could be found trading stories with passing merchants and bards. The more he learned the more he wanted to know. More than anything he loved uncovering hidden connections between manuscripts from different authors and eras. After coming of age and serving the requisite time in his clan's militia, his sights turned to the troves of knowledge he knew were scattered across the land, and so he set out on his own one day to see what he could learn.

## Potential Plot Hooks

Amberscale has discovered what he interprets to be an ancient prophecy that tells of the second rising of dragons at the hand of a Dragonborn, through the use of a long lost war machine from a long forgotten war. It has started to consume his dreams. He considers this to be a noble endeavor that will restore balance to the natural world. (He may be misguided in his interpretation, but he's convinced himself he's correct.)

**Comment by zmoazeni** [comment]
I love it. Approved!

**Comment by chrisbloom7** [comment]
PDF added to the description!

**Comment by zmoazeni** [comment]
@chrisbloom7 well...shit. I feel silly. I thought only the owners of the character sheet could print out the PDF. Yeah, so given a person's DNDBeyond link a GM should be able to get access to them all. Fantastic.

One more thing I'll ask you to do. Can you start a wiki page for your character? You'll be the first person to do it. But I think it'd be great to close this issue and move this info with the important links to the Wiki.

I'll try and put a template together eventually. But don't feel you need to bring over any of the stats, spells, and other fiddly bits from dndbeyond.

**Comment by chrisbloom7** [comment]
@zmoazeni do you think the wiki page for characters should basically be the same as what's in the issue description? Are you looking for more info there, or less?

**Comment by chrisbloom7** [comment]
Looks like @djigneo went that route for https://github.com/our-stories/west-marches/wiki/Character:-Karris,-the-Namer, so I'll follow suite.

**Comment by chrisbloom7** [comment]
Copied to https://github.com/our-stories/west-marches/wiki/Character:-Amberscale-(Dragonborn-Sorcerer-3)
