### ISSUE TITLE
Session 1: It freaking begins...

### ISSUE THREAD

**Issue by zmoazeni** [our-stories/west-marches#34]
Friends. We now have enough people to begin our first session. Let's see if we can make it happen.

## Session information

**Date:** Aug 9th 6-9PM Eastern / 3-6PM Pacific. Remember please be 15 minutes early.
**Location:** [Zoom](https://us02web.zoom.us/j/81456089813)

## Players

1. @crimsonknave / [Quay](https://github.com/our-stories/west-marches/wiki/Character:-Quay)
2. @chrisbloom7 / [Amberscale](https://github.com/our-stories/west-marches/wiki/Character:-Amberscale-(Dragonborn-Sorcerer-3))
3. @djigneo: [Karris](https://github.com/our-stories/west-marches/wiki/Character:-Karris,-the-Namer)
4. @thyeggman / [Otru](https://github.com/our-stories/west-marches/issues/38)

GM: @zmoazeni 

## Details

* [x] **Scheduling:** Please take a look at [this schedule](https://doodle.com/poll/wgh6ugfi9q3mz838) and let me know if none of those times work for you. Or if we need to schedule it out further. Poll is in Eastern times.
* [x] **Players have chosen their character and updated the session above**
* [x] **Players and GM have confirmed they have stable internet, audio, and video hardware.** (Please use a decent mic. That helps so much).
* [X] **Is this a continuation?** Nope!
* [x] **GM should post a "tavern"-type RP here in the thread. To allow characters to "meet" each other via text**
* [x] **GM to share a Zoom link.**
* [x] **How deadly does the party want the session?**
* [x] **Is the party okay with the game recording being posted?**?
* [x] **GM should post a couple of adventures for the characters to consider.**
* [x] **Has an adventure been chosen?**
* [x] **Has the tone been chosen? laid back, silly, serious, heroic, terrifying, depressing...**
* [x] **Is the GM ready to start the game?**

**Comment by crimsonknave** [comment]
Are we all in Eastern time? What timezone is the poll based on?

**Comment by zmoazeni** [comment]
@crimsonknave great point. Updated the description above.

**Comment by zmoazeni** [comment]
@djigneo @crimsonknave I've updated the poll. I was silly by adding a single block for the weekends. Now there are multiple 3-hour blocks. That should make more sense to figure out what fits for everyone.

**Please go back and check your poll choices** ❤️

**Comment by thyeggman** [comment]
I'm in PST so the weekdays will be tricky for me.  I may try to change my work schedule for a day so I can free up a spot though.  I guess my participation is also contingent on making a character... Just have been too wrapped up in my own content recently :P

**Comment by zmoazeni** [comment]
@thyeggman No problem! It happens! I think I may run multiple ad-hoc sessions as we get started and our legs underneath us. So even if you can't attend this one, I (or eventually other players) will spin up another.

**Comment by zmoazeni** [comment]
Alrighty gang! It looks like **August 9th from 6-9PM** Eastern works for everyone.

That's not a lot of time, but I can manage. We need to finish several more steps before our session can begin. Please take a look at the top list and let's burn through it all.

I'm going to post a few comments and I'd like you to vote via emojis to help us sort out our next steps.

**Comment by zmoazeni** [comment]
## How difficult do you want this to be?

Drop one or more emoji's on this comment to vote. Feel free to reply if you have questions first.

* :smile:"Mild" should be a cakewalk, and we can let loose. 
* :tada: "Medium" will require some strategy and resource management.
* :rocket: "Spicy" you'll likely have to run away at least once.

**Comment by zmoazeni** [comment]
## Are you okay with the recording being shared with the community?

I'd like to share recordings of this after the game. I think it's a great way to get folks into this community by seeing how the games go.

* :+1: Sure!
* :-1: Just shared with us please.
* :heart: I don't care that much.

**Comment by zmoazeni** [comment]
## Choosing the adventure

**_The burly barkeep sits back on his stool behind the bar of the Sunken Hazelnut tavern. You can't quite tell if his heavy lidded eyes are even open, and he doesn't give any hints to prove otherwise. A pair of servers, woman and man, head back and forth serving food and drinks. The common room is lightly populated in the early evening. The room is quiet except for the murmur of conversation and the occassional laughter. The patrons look like hardworking trademen finishing a hard day, relaxing in their usual spots._**

_Each of you enter. Separately or together. You decide. If you haven't met yet introduce yourself. The party should form here in the thread and have decided what adventure to embark on by the time we start our session._

_At some point in the evening..._

---

**_Adventure 1: A man stumbles into the tavern. His face white with shock. A few people, presumabably his friends, look up and say his name. The party sees concern in their eyes as the man ignores them completely. He mutters to himself, but loud enough for everyone to hear "The frogs... the frogs destroyed everything..."._**

**_His friends, now very worried, drag him to their table and push mug after mug in front of him. He stares at them blankly. He starts telling his group of how the giant frogs attacked the fishermen, killing Frelin. He ran but not before he saw them drag Frelin's body, along with the fishing nets, back into the water._**

---

**_Adventure 2: A woman runs into the tavern yelling for help with a deep voice. She clearly doesn't look persued by anyone. In fact, you would be surprised who would be able to harm her. She stands 6ft with thick corded muscles. With a leather apron and soot staining he face, you assume she is a blacksmith._**

**_"Toni! Gather round ye lazy no good bastards! Toni is in trouble!" The party watches as no one in the tavern stirs to help her. "They took him!" "Who took him?" one voice in the crowd asks, with the barest curiosity. "RATS! Get off yer asses an' help me get him!" She hefts a large blacksmith hammer from her belt loop and surveys the tavern. No one makes a move._**

**_"Curse you sons o' pigs!" and she spits on the ground before storming out of the tavern. Probably to ask for help elsewhere. The party can catch her if they follow her now._**

**Comment by djigneo** [comment]
I suggest we vote on adventure, then RP to get to the decision.

- 🎉 Adventure 1
- 🚀 Adventure 2

**Comment by zmoazeni** [comment]
Also: let's agree on the tone of the session. I'm listening to Guards! Guards! with my kids. So without direction, I may take it into some silliness.

**Comment by djigneo** [comment]
**_The adventurers had all met before tonight, over the last couple of days. Finding commonalities in being adventurers and needing a new job, they decided to meet tonight, each bringing any leads they had found in hopes of a job that brings enough coin, well and enough renown to get better paying jobs, at least. The evening had not gone so well, the leads were sparse and the group had largely decided tonight was another drinking night, when suddenly a cry for help was heard.

Quay convinced the group that this was as good a job as any. "We are adventurers after all, no sense in sitting around!"_**

To this point, I imagine Karris has experienced the following with the other party members:

- Finds a bit of a kindred spirit in Amberscale, who also has a hunger for learning magical secrets as she does.
- Found common interests with Quay in their mutual knowledge of music and enjoys his general outgoing nature.
- Doesn't know much what to think of Frog, but secretly admires his tattoos and has done some calligraphy in her spare time inspired by the tribal designs of his clan.

**Comment by thyeggman** [comment]
_**Otru had met the others just two nights ago.  On one of his rare nights in town, he saw a few of the loggers heading into the Sunken Hazelnut.  He wandered the tavern, a rarity for him, and sat alone at one of the tables.  Having given up hunting, he was somewhat stalled in his new passion for the druidic arts.  Turns out magical training cost more than his previous recluse's lifestyle could afford.  He has never particularly sought out wealth, but he wants to be able to protect the wilds.**_

_**He overhears a conversation about magic from a few tables over.  He turns around and sees an odd group of a Gith, a Dragonborn, and a Tortle.  They seem to be talking about earning some money.  Otru goes over to the table and stand there awkwardly for a bit, listening to the two mages chat, not wanting to interrupt.  They seem more experienced than he, but he tries to absorb as much as he can.**_

_**He jumps slightly as it's not the mages, but the Tortle, Quay, who casually invites him to sit with them.  He introduces himself to them and they get to chatting.  It seems that their interests align, and without an official acknowledgement, he becomes part of their group.**_

Otru's short experiences with the others:

- Amberscale and Quay often seem to be vying to be the loudest voice in the room, but listening to their banter makes Otru feel comfortable
- Otru is especially interested in Amberscale's prophecy of the second coming of dragons and the restoration of the natural world
- Quay often intimidates Otru, but he is grateful that Quay so easily accepted him into the party's company
- Karris's story intrigues Otru - he has had some problems coming to terms with the actions of the townsfolk, and her self-assuredness gives him some small amount of confidence

**Comment by crimsonknave** [comment]
_Quay approaches the fisherman's table after a bit, waiting until the man had gotten some color back._
**"Perhaps my friends and I can help? I can't guarantee anything, but we can at least take a look around if the City Guard isn't able to."** _Quay glanced back to his friends and notices Karris glaring daggers at him. He swallows a bit and gestures for them to come over._ **"I'm going to see what I can do to help, who's with me?"**

_As they leave the tavern he turns to fisherman,_ **"Have these frogs troubled you before?"**

Quay is delighted to have some new friends. First, friends tend to be handy in a pinch and second, audiences get bored of stories if they're all about the same person.

* Quay finds Karris fascinating. His endless questions went from flattering to annoying fairly quickly. Karris made a few cutting remarks before he got the message and she was surprised when he seemed to be genuinely thrilled to be insulted. 
* Otru is a puzzle to Quay. But, then again, most people don't really make sense to Quay. He'll never really understand why everyone wants to stay in the same place doing the same thing over and over.
* Quay and Amberscale have a running dialog about the things they've seen and learned in his travels. It hasn't slipped past Quay that he seems to be sharing more than Amberscale, but it also doesn't really bother him.

**Comment by zmoazeni** [comment]
@crimsonknave 

> Is there a city guard? Why are they not doing anything?

There is a town militia, but it's heavily volunteer based. There are many professionals, but mostly citizens who will pick up arms and understand rough orders from the captain. Only to avoid the town from being overrun.

There are too many outside threats for the militia to keep complete safety, even with in the borders. That is just a fact of life for the townsfolk

> Have the frogs attacked before?

This is new to everyone in Waldenstone. But not really that much of a surprise. This is the life out here.

> Do we know why they attacked?

Nope. But you can investigate and learn more.

> Where is the fisherman from?

He is a local. Waldenstone sits near the Lucidean Ocean. There are also rivers that lead to the ocean, along with several deltas that are ripe for fishing. 

---

You all are welcome to ask more questions too to check assumptions your characters may have without RPing to learn more.

**Comment by chrisbloom7** [comment]
Amberscale came to Waldenstone a few weeks ago, having grown weary of trying to defend his research to the "scholastic simpletons and thought police" of the academic guilds in the neighboring cities. A secretly disenfranchised guild member confided to Amberscale that he should stop wasting his time prowling the "selectively groomed stacks of acceptable knowledge" that the self-aggrandizing College of Neutral Thought, Research, Observation, and Literature "allowed" Amberscale access to. Instead, given Amberscale's obvious abilities to handle himself, this confidante offered a tantalizing alternative: head to the frontier and seek out lost arcane manuscripts before the College could find them. These could then be delivered via an underground network to the library of a secret society, working quietly to strip the College of its influence. The confidante explained that if Amberscale could prove himself capable and dependable, perhaps an introduction could be made to this secret society. It was tantalizing enough for Amberscale to depart for Waldenstone that very night.

Amberscale first saw Karris as a unique extraplanar source of arcane knowledge that he could tap into, but has come to know her as someone who is also strong and capable, handy to have at his side in the vast wilderness beyond the walls of this border town. It helps that she too hunts for arcane knowledge, though he hasn't yet confided in her what he intends to do with whatever he finds, and he is watching her closely to see what she does with her own finds.

Otru stood out to Amberscale due to his copper skin and intense scars, clearly a survivor of some tragedy. Amberscale took pity on the young Elf, less out of sympathy for his pain than from a narcissistic need to equate Otru's physical suffering with Amberscale's own perceived intellectual suffering at the hands of the College - despite the obvious flaws in this relationship from an outside perspective, Amberscale's concern for Otru is sincere even if misguided.

Quay is a mystery of a different sort in Amberscale's mind. Amberscale has never suffered fools, so while he initially assumed Quay would be plodding and dull, the Tortle perplexes him with his outgoingness, boasts, and obvious physical prowess. There is also something in the rivalry between Quay and this Golden Beard that is deeply gratifying to Amberscale - the constant tit-for-tat as each vie for the upper-hand makes for good entertainment, and Amberscale does appreciate a good social upset.

As to this issue with the frogs: What could have caused this aggression? Could it be arcane in nature? Are these beasts under the influence of sorcery? Certainly worth exploring, and to be honest Amberscale's purse is feeling lighter than he's comfortable with.

**Comment by chrisbloom7** [comment]
_A little meta:_

_Amberscale is a conspiracy theorist, and I hope the GM won't feel pressured to try to work his theories into facts in the universe. In fact, I would love to see Amberscale stumble over his theories - he will still believe them to be true and will look for ways to justify his thinking even if he doesn't find what he's looking for, which I think could be interesting to explore._

_Secondly, as a party member Amberscale has his flaws - I am not trying to RP him as evil or uncaring but rather as someone who is unaware of his own failings and deeply lawful to his own ideas. If that starts to come across as evil or backstabby, or just generally unfun, please call me out on it - that's not the character I want to play._

**Comment by crimsonknave** [comment]
Quay had a good time adventuring with his new friends. He's sad, but not surprised they weren't able to save the fisherman. Mostly however, he's very confused at the confidence the Bullywugs had at the start compared to their actual combat prowess. Hopefully Slager will prove more interesting. Right now he's afraid they'll just go back and tell the fishermen that their friend was killed by some weak frogmen for no reason.

**Comment by chrisbloom7** [comment]
From Amberscale's journal: _I was disappointed to learn from Otru that the perpetrators of the fisherman's murder were Bullywugs, who apparently have a natural tendency towards mayhem when they establish a new territory. I was very much hoping for an arcane explanation... Still, a few of them mentioned a `Slager` - perhaps this being will prove to be more interesting than some primitive amphibians with a savage nature. As to my companions: Karris continues to prove herself to be an intellectual equal who has keen perception and keeps a level head; Otru and Quay have a predisposition towards aiding the fallen which I admit I found to be tiresome, but they did manage to gather some information through their methods so perhaps I shall hold my tongue next time. All told they do not lack of courage and I found myself proud to be in their midst._

**Comment by djigneo** [comment]
From Karris' journal:
_I was worried at Quay's willingness to let himself be surrounded by the strange frog-like creatures we encountered, but I guess I had nothing to worry about! What a specimen he is, exhibiting great physical prowess as he dominated practically all of them single-handedly. He's definitely worth every copper his owner paid for him. Strong, and a great swimmer too.
I was also pleasantly surprised at my companion's cleverness in getting the drop on the bullywugs in the cave. By the time I caught up with the others, the fight was practically over.
Amberscale breathes like a real dragon! Somehow I get the feeling that he was bored and looking for a real challenge. It'll be interesting to see what he does when he lets loose.
Otru seems to be resourceful and knowledgeable about the creatures in this world, he seems like a professional.
It'll be interesting to see if we can uncover the cause of this attack, but I hope we don't run into too many more of these frog creatures -- they creep me out. I'm just glad I'm wearing heavy armor._

**Comment by zmoazeni** [comment]
For this session each party member receives:

* 1000xp
* 12sp 3cp

**Comment by thyeggman** [comment]
From Otru's Journal:

_It is disturbing that Bullywugs have infested the area.  I recalled a trader talking about them a few months ago after some thought.  His descriptions of them did not do them justice.  Quay was impressive, if slow, in the water, and did a lot of the initial search.  Still becoming familiar with my spirit totems, I summoned Hawk prematurely.  She was not able able to help, and I was not able to summon her again.  I shall have to learn to summon them at more useful times._

_Amberscale and I made a particularly unfortunate blunder when scouting the inlet that the Bullywugs had retreated to, and alerted them all to our presence.  Quay, being exceptionally sturdy, took most of the brunt of their attacks.  I wasn't so keen on killing them all without knowing why they were preying on the locals, so I spared one who ran off into the cave.  During the attack, Amberscale used his fire breath, which admittedly put me on edge.  Luckily we were standing in water so there was little harm of a blaze._

_When we caught up to the creature, Quay was able to talk with him.  Although he was out of sorts, his words were ominous, warning us of our impending death at the hands of Slager.  We continued on into the cave where Amberscale devised a clever distraction that allowed us to rout them in quick fashion._

_I'm still not sure what to make of Karris, she seemed to keep her distance from the group but did provide keen insights.  Nonetheless, she acted intelligently in our combats._

**Comment by chrisbloom7** [comment]
@zmoazeni are we doing XP based leveling? I thought we had last left it as milestone based on the number of sessions a character participated in. Or is this a hybrid of sorts so there's still some grinding to do at later levels?

**Comment by zmoazeni** [comment]
@chrisbloom7 Yeah we're XP leveling (I should put that somewhere in the repo). I had considered milestones or x sessions per level, but I think that breaks down quickly with a fluid group of players and GMs.

I figured with straight XP it would be easier to track on a per character basis.

That said, I was planning on doling out XP for finishing an adventure too. And it's not strictly about "how many monsters did you kill". I calculated this as:

* You all haven't finished the adventure, and that's okay!
* You all encountered two separate groups of 5x bullywugs. Based on my math using dndbeyond's encounter builder is 500xp each.
* I know that a few ran off and joined that 2nd group. But I consider that "taken care of". I recognize that the DMG and a few blog posts I've read mention to give partial XP, but for these games I'm not interested in splitting hairs.
* One thing I haven't mentioned is that I would like characters to have a long rest to take advantage of a new level. They don't have to be back in town, but a long rest will do.

Let me know if you (or anyone else) have any other questions!

**Comment by zmoazeni** [comment]
So you all went to investigate the fishermen, and I said I retconned the Blacksmith. [I decided to write a thing](https://connectionrequired.com/stories/waldenstone/blacksmith).

**Comment by crimsonknave** [comment]
@zmoazeni I'm not trying to argue for less xp, but, I'm a bit confused,maybe I'm mis-remembering the xp rules (it has been a while), but my reading of the xp from those encounters is that each set of 5 is worth 250 xp (I believe that the adjusted xp is just for the purposes of calculating difficulty and not awarded). So, in total we earned 500 xp which is then split 4 ways. So, we'd have earned 125xp each.

**Comment by zmoazeni** [comment]
> (I believe that the adjusted xp is just for the purposes of calculating difficulty and not awarded)

@crimsonknave Hrm. I did not think that XP boost was only for calculating difficulty. In my opinion if it's more difficult, you all get rewarded more too. Otherwise I'm being kind of an asshole to send difficult encounters to you all constantly with no benefit.

However, something I think I did blunder on is that I just gave everyone _the full party XP_ that should have been split 4 ways.

![D D Beyond - Encounter Builder for Dungeons   Dragons (D D) Fifth Edition (5e) 2020-08-12 13-17-37](https://user-images.githubusercontent.com/314/90046302-4a6fb600-dc9e-11ea-9212-139b6476ec2c.png)

If it's 2 encounters of 👆 that would be 1000XP total **for the party** which means 250XP **per member**.

Am I math'ing right here or am I way off? If there's still a misunderstanding here, let's move the discussion to a separate thread and you can help me out where I'm being foolish.

**Comment by crimsonknave** [comment]
Your math looks good to me.

**Comment by zmoazeni** [comment]
@crimsonknave thanks for speaking up! I didn't know what I didn't know and I clearly botched that.

**Comment by zmoazeni** [comment]
I think we're good to close this out!

**Comment by zmoazeni** [comment]
Recording is now live: https://www.youtube.com/watch?v=O0vzM9vCYEQ
