### ISSUE TITLE
Character: Frog Hoppa

### ISSUE THREAD

**Issue by ezcawi42** [our-stories/west-marches#35]
_Please fill out your character as much as possible. Feel free to edit as much as you need. When you are all set, assign @zmoazeni to the issue._

**Name:** e.g.Frog Hoppa

_Tip: If you need help with [generating a name](https://www.fantasynamegenerators.com/dungeons-and-dragons.php)_

* Race (and subraces if any): Tiefling
* Class(es) w/Levels: Warlock 3
* Alignment: Chaotic Good

**Character sheet:**
https://www.dndbeyond.com/profile/ezkawaii/characters/33409556

## Appearance:

_What does someone see when they glance at your character? Do they even notice them? What impressions does your character give when speaking? When they're pissed?_

Frog is a green tiefling with a shaved head and short slightly curved horns. His body is covered in black striped tribal tatoos that seem to change over time. He's pretty chubby, as though he had the benefits of a lot of food and not much menial labor. He wears a set of rough leather armor embellished with beads, feathers, and snakeskin bands which anthropologists would recognize as coming from a swamp dwelling tribe of tieflings. He carries a staff affixed with a dark green gem at the top.
He and his belongings are perpetually damp and doesn't see why that is weird.

When speaking, Frog is smooth and a little too charming. He will always try and steer the conversation into matters of the weird and arcane, and doesn't have much interest in mundane matters.
In conflict, Frog will first try to deflect the issue or magically charm his way out of the situation.
When angry, Frog will again first turn to trickery and magic before physical confrontation.

**Age:** 30

**Height:** 5' 10"

**Weight:** 200 lbs

**Eyes:** Glow in different colors.

**Skin:** Green

**Hair:** Black but usually shaven

## Backstory

_Your character wasn't born yesterday. Where did they come from? Have they raised themselves from the gutters as a child? Were they pampered among the highest royalty? Who the hell is your character?_

_Even though other players can read your character's background, their characters won't act on it unless it is shared with them in game.

Frog grew up in a tribe of swamp dwelling tieflings who worshipped a amphibious archfey as a god. When he was young, he was chosen from among the children of the tribe by the archfey to make a magical pact and began training in magical arts. Somewhat of a celebrity in his village, Frog was always a little too well fed by the rest of his tribe but never had to do any work other than his magical training. When he reached adulthood, Frog was sent out as the emissary of the tribe and archfey to the world outside the swamp. For his tribe, he negotiates trade and other diplomatic deals with different towns/factions, but his personal goal is to attain as much magical power as possible.

Frog has absolute loyalty and trust in his patron, and very temporary loyalty to anything else.
He has utmost confidence in his ability to solve any magical conundrum or commune with any creature.
He doesn't see much problem with deception, disguise, or magical charm to attain his goals, and doesn't understand why people are angry with him afterwards.

Frog is interested in magic and power of any form. He has joined several religions and cults to learn their eldritch ways, only to back out once he realizes they want a more exclusive commitment. 
Because of the way his magic was attained, he is a wheeler and dealer.

## Potential Plot Hooks

_People are flawed. Not even you dear adventurer are perfect! Has your character pissed someone off? Are they outlawed from a certain town for a... misunderstanding? Do they struggle to overcome something: a paranoia, a physical limitation, an addiction?_ 

_This is entirely optional, but depending on the flare the approving GM may award an XP bonus while your character struggles with their demons._

Frog  enemies as the result of wanton magical charming, and jilted friends/lovers he had left behind when he decided to move on from an area.

From bonds - When frog was leaving one of his cults, he happened to take a particularly important book of evil and eldritch secrets, which he has yet to fully investigate.

If the swamp he is from is in the wilderness, he is motivated to explore to protect his tribe from random monsters and such.
If swamp is not in the wilderness, he could have traveled to Waldenstone at the behest of the tribe/patron to investigate something, or be on the run from a particularly angry cult.

Frog is a maker of deals, no matter how foolish they may be. While he always attempts to make sure the deals are more in his favor, he is not nearly as clever as he thinks he is. He will always succumb to eldritch temptation.

**Comment by zmoazeni** [comment]
@ezcawi42 this is amazing. You have the option to start your character at level 3 if you like. There's also a session being [scheduled now](https://github.com/our-stories/west-marches/issues/34) if you'd like to join up with it and the timing works.

**Comment by zmoazeni** [comment]
Also please push this into a wiki page :heart:

**Comment by ezcawi42** [comment]
Thanks, I will up the level to three on dndbeyond. I think i need extra permissions to contribute to the wiki/assign myself to sessions.

**Comment by zmoazeni** [comment]
@ezcawi42 Invited to the org. Once you accept it you should have permissions.

**Comment by ezcawi42** [comment]
Great, thanks!

**Comment by zmoazeni** [comment]
I think I've set this up so that anyone can update wikis now without being part of the organization.

**Comment by zmoazeni** [comment]
https://github.com/our-stories/west-marches/wiki/Character:-Frog-Hoppa
