### ISSUE TITLE
Session 2: Holy shit the first one filled quickly...

### ISSUE THREAD

**Issue by zmoazeni** [our-stories/west-marches#36]
The first session #34 filled up too quickly. Let's just open up a new session now and see who is interested!

![](https://media.tenor.com/images/aafb5537784255395b1871b7ef5e0d80/tenor.gif)

## Session information

* [Meet-n-greet poll](https://doodle.com/poll/7c5vitnaecvmrats) - [Aug 22nd 3-4PM Eastern](https://everytimezone.com/s/04c2b0e3) - [Meeting URL](https://us02web.zoom.us/j/83122003724)
* [Session poll](https://doodle.com/poll/czu3k7wut32nh3ub) - [Sept 4th 6-9PM Eastern](https://everytimezone.com/s/d395f2d0) - [Meeting URL](https://us02web.zoom.us/j/85638763198)

## Players

1. @ezcawi42: [Frog Hoppa](https://github.com/our-stories/west-marches/wiki/Character:-Frog-Hoppa)
2. @crimsonknave / [Quay](https://github.com/our-stories/west-marches/wiki/Character:-Quay)
3. @GoJustME / [Garn](https://github.com/our-stories/west-marches/wiki/Character:-Garn)
4. @djigneo / [Karris](https://github.com/our-stories/west-marches/wiki/Character:-Karris,-the-Namer)

GM: @zmoazeni 

## Details

* [x] **Scheduling:** This is on @zmoazeni to put together a poll to find this. I'll update this after we get at least 3 players.
* [x] **Players have chosen their character and updated the session above**
* [x] **Players and GM have confirmed they have stable internet, audio, and video hardware.** (Please use a decent mic. That helps so much).
* [x] **Is this a continuation?** Nope!
* [x] **GM should post a "tavern"-type RP here in the thread. To allow characters to "meet" each other via text**
* [x] **GM or Players to share A/V link (like Zoom) or decide some other mechanism (like Discord).**
* [ ] **How deadly does the party want the session?**
* [x] **GM should post a couple of adventures for the characters to consider.**
* [ ] **Has an adventure been chosen?**
* [ ] **Is the GM ready to start the game?**

**Comment by crimsonknave** [comment]
So, if we're hard capping to 4 players per session, I think it might make sense to pick a time and see who can show up. Otherwise, we might get into the situation where some players keep saying yes (Why wouldn't I sign up to play at a yet to be determined time?) and then the schedules prove hard.

**Comment by zmoazeni** [comment]
@crimsonknave Yeah totally agree. I was going to wait until we picked a time for the previous session before posting the poll for this one. Since my schedule is dependent on both.

**Comment by crimsonknave** [comment]
I guess my thought was more that you should pick a time or two that you can do and let the players who can make that join instead of having it be whoever sees the issue first get in and then struggle with scheduling.

**Comment by zmoazeni** [comment]
I haven't forgotten about this session. I just have some more to wrap up from Session 1 before I can push on this and give some more clarity around my schedule. I will this week though, don't worry ❤️ 

I may schedule this further out so we can have more time to RP.

Or perhaps we can schedule a mini Session-0 for it so everyone can meet-n-greet well before the actual game. I think that would go a long way.

**Comment by djigneo** [comment]
I'm interested, but would need to have an idea on schedule before I could commit.

**Comment by zmoazeni** [comment]
Alrighty gang, if you check the top of the thread, I have a couple polls up.

I want to try an hour meet-n-greet. Let's just say hello and get to know each other before we play the game. I think that may help.

**Comment by zmoazeni** [comment]
## Adventure 1

_A cheap tattered parchment is found nailed to a signpost near the Inns where adventurers frequent._

_"Please help. Our farm is being overrun by these lizard monsters. Our family can't defend much longer. -Bardol"_

_There is a scribbling of a map showing Bardol's farm to the North East of Waldenstone_

## Adventure 2

_Rumor has spread in certain circles that two merchant families with a longstanding feud is coming to a head. The Warners and the Fosters have fought economically over local mining rights. Both are discreetly looking for  help in order to wrestle control from the other._

**Comment by zmoazeni** [comment]
## How difficult do you want this to be?

Drop one or more emoji's on this comment to vote. Feel free to reply if you have questions.

* :smile:"Mild" should be a cakewalk, and we can let loose. 
* :tada: "Medium" will require some strategy and resource management.
* :rocket: "Spicy" you'll likely have to run away at least once. Mo' danger, mo' rewards!

**Comment by zmoazeni** [comment]
## Are you okay with the recording being shared with the community?

I'd like to share recordings of this after the game. I think it's a great way to get folks into this community by seeing how the games go.

* :+1: Sure!
* :-1: Just shared with us please.
* :heart: I don't care that much.

**Comment by GoJustME** [comment]
I'd love to aswell but depends on scheduling, voted in the poll.

**Comment by zmoazeni** [comment]
@GoJustME I added you to the roster above.

@djigneo @crimsonknave @ezcawi42 @GoJustME It looks like we have a soft consensus for Sept 4th 6-9PM Eastern. Does that work for everyone?

**Comment by zmoazeni** [comment]
@djigneo I went ahead and added you to the roster above. Feel free to RP in the thread until the game to get a feel for each other's characters. It'll help us hit the ground running when we meet on Zoom.

Also it'll help me if you all can vote on the Adventure sooner rather than later. That way I have a little more time to prepare.

**Comment by djigneo** [comment]
I put it on my calendar and voted on the adventure.

**Comment by zmoazeni** [comment]
Hey folks. I'm going to drop the whole recording stuff for now. Let's just have a good time.

**Comment by zmoazeni** [comment]
I solidified the dates at the top. @GoJustME sorry, I know that both times aren't the greatest for you. Let me know if I need to expand more options.

**Comment by GoJustME** [comment]
> 
> 
> I solidified the dates at the top. @GoJustME sorry, I know that both times aren't the greatest for you. Let me know if I need to expand more options.

Looking good, times are fine 👍

**Comment by zmoazeni** [comment]
## Session awards

1000XP per player
62gp 8sp 8cp total (15gp, 315sp, 2cp per player)

**Comment by crimsonknave** [comment]
_Quay is troubled by his latest adventure. There are too many things that don't add up... Too many questions. The farmer Bardol was too quick to judge the Kobolds and accused them of lying when they were mostly telling the truth, he's likely to cause trouble in the future. Why was the egg of a Kobold noble just laying out in the woods near their lair? How can we sever the bond between the boy and the egg? What will happen to the Kobold if it hatches and lives with that family? Will Bardol treat it well or like the others of it's kind will he attack it and assume ill intent at every turn? Just how many Kobolds are in that lair? Can we survive an encounter with them? Can we avoid killing all of them without letting them kill an innocent child?_

_There is much to think on. I think tonight I shall give a more mellow performance as I ponder these questions._
