### ISSUE TITLE
Character: Otru

### ISSUE THREAD

**Issue by thyeggman** [our-stories/west-marches#38]
I used the point assignment for skills, and set my character to level 1.  Not sure if the recommended starting level is higher

**Name:** Otru

* Race (and subraces if any): Elf
* Class(es) w/Levels: Druid 1
* Alignment: N

**Character sheet:**

https://ddb.ac/characters/33446787/AJS0Rk

PDF: https://www.dndbeyond.com/sheet-pdfs/thyeggman_33446787.pdf

## Appearance:

**Age:** 38

**Height:** 5'8"

**Weight:** 114

**Eyes:** Amber

**Skin:** Copper

**Hair:** Brown

**Description:** His skin is copper but he has large patches of pale, pallid skin on his left side where he was badly burned in a forest fire (see below).  He has long, uncut hair, and wears light leather armor.

## Backstory

Otru grew up on the outskirts Waldenstone with his parents (Traethym (mother) & Droic (father)), who are saddlers.  He could always be found wandering into the wilds that ringed the city.  As Otru grew, so did the city, driving back the wilds as it did.  Once he was old enough to live on his own, he became a hunter and lived outside the city, enjoying the peace that it afforded him.  He would only come back into town to sell the meat, pelts, and other things that he gathered.  Otru lived this way for over a decade.

One day, Otru woke up to find one of his hunting grounds being logged for more farmland.  He didn't really have a rapport with the townspeople, reclusive as he was, so he retreated further into the wilds.  Otru had always known of the dangers of the wilds, and had seen more creatures act up as their lands were taken away.  He kept his distance from them, but would soon no longer be able to.

He stumbled into a den filled with dozens of Giant spiders.  They went into a frenzy and wrapped him in their webs, and then began to attack the loggers.  Otru was trapped, but in the meantime, the whole forest was being covered in webs as people were attacked.  In their panic, they decided to burn the webs to drive the spiders out.  The spiders fled, but Otru was left to die.

Otru had begun to accept his fate when he suddenly dropped to the ground.  The web was cut open and he was left staring into the eyes of a strange creature with skin like stone.  The oread paused and looked at him knowingly, then turned and left.

Still in the midst of a burning forest, Otru struggled out of the remains of the web and stumbled through the scorching heat, clothes in tatters.  He was barely conscious, but horror still registered at what the loggers had done.  The whole forest could be lost!  Plumes of smoke billowed into the sky.  Otru could see his whole way of life crumbling before him, and prayed to whichever gods could hear him to protect the forest.  Miraculously, the sky opened up and rain began to fall, shortly extinguishing the fire.  He crawled back to his parents' home on the edge of town, and they were able to get him help, but not without leaving Otru badly scarred.

The experience gave Otru a newfound passion for nature, and so he gave up hunting began to study the druidic arts.  He wants to protect the land that had given him so much.

**Goals:** Learn more about the secrets of the wilderness.

## Personality / Demeanor

Otru is pretty guarded, especially in large groups of people.  However, when talking to others or negotiating, he is straightforward and decisive.  He is terrible at telling lies.  Unless someone is especially outgoing, the usually don't approach him, partially due to his scarring.  He has a keen ear, so he can pick up a lot about the flow of life in the city.

## Potential Plot Hooks

- Maybe the rain at the fire was actual divine intervention?
- Why did the oread save him?  Are there more in the hills/forest/etc?

**Comment by crimsonknave** [comment]
I can see there being some tense interactions with the loggers as well.

**Comment by zmoazeni** [comment]
Oh hell yeah! A LOCAL! Approved!

**Comment by zmoazeni** [comment]
Doh, I closed too soon. Can you create a wiki page with this info?

**Comment by thyeggman** [comment]
Created a wiki page, will close this now.
