### ISSUE TITLE
Character: Quay

### ISSUE THREAD

**Issue by crimsonknave** [our-stories/west-marches#4]
**Name:** e.g. Quay

**Class** Bard

**Background:** Galdiator

**Race:** Tortle

**Alignment:** Neutral Good

## Appearance:

**Age:** 16

**Height:** 5'8"

**Weight:** 480lbs

**Eyes:** Sea Green

**Skin:** Mottled Grey and Yellow

**Hair:** He does not currently have a pet rabbit (`ba` `dum` `tish`)

Description of the character that others would notice if they met them. Distinguishing tattoos, markings, mannerisms, voice.

Flesh this out as much as you can. This won't be set in stone.

## Backstory

Quay, like many of his race, instinctively seeks out adventure. He earns his coin primarily by performing in stage fights. His flair for the dramatic makes him a popular gladiator. When he's not in the ring, he can often been found in a pub if there's not a festival or circus around. He loves to make friends and share stories, but his honest nature have gotten him in trouble with a wide assortment of folks and even run out of one town. Well, to be honest, it was probably more the fact that he asked some rather inappropriate, personal questions to the mayor because someone dared him to that really got him kicked out, but that's not quite how he'd tell it.

He's recently arrived in Waldenstone and is looking to learn about the people here as well as make a name for himself along the way.
## Notes

I have made him up as a fifth level character here so I can work out a vision for what he'll become: https://www.dndbeyond.com/characters/21101057

## Plot Hooks

Quay will be interested in anything that sounds like an adventure. He's also always up for helping an old friend or making a new one. He often gets into trouble for speaking his mind when he thinks something is wrong.

**Comment by zmoazeni** [comment]
@crimsonknave Whoa. I didn't even know about the Tortle race. This is sweet! A Bard/Paladin split!? Niice. This keeps popping in my mind: 

![](https://i.pinimg.com/736x/a3/c1/7b/a3c17b8b67ea6268f9a9ef16cabef440.jpg)

Can you flesh out the description a little? We'll want that for other characters to know what to expect.

**Comment by crimsonknave** [comment]
Updated with some backstory. He's going to play pretty interesting (If I end up playing him, I do have a number of character ideas). He's first and foremost a melee fighter and I'm expecting once he gets his second Paladin level most of his spell slots will be used Smiting. He'll never have great Charisma since he's more focused on STR and CON first, which means his spells are going to be more utility that don't rely on stats (think `Knock` or `Feather Fall`). But, all his spells are for combat because they can fuel Smite!

**Comment by crimsonknave** [comment]
@zmoazeni I think Quay is all set and who I'll be starting out playing as. He's the one I was most excited about and I felt I could fully fit out the backstory for.

**Comment by zmoazeni** [comment]
Approved!
