### ISSUE TITLE
Session: J-1

### ISSUE THREAD

**Issue by djigneo** [our-stories/west-marches#42]
August 28th 7:00 PM - 11:00 PM CST

[Schedule poll](https://doodle.com/poll/pe8g7zb4ckr5f8cg)
[Roll 20 campaign](https://app.roll20.net/join/8370216/2KlGhg)

* Ensure party is between 2-4 characters. Include wiki links for each character.
* Have the characters met each other yet?
* Is this continuing a previous session? No
* How deadly does the party want the session? (more deadly, more treasure).
* Not planning on recording the session.
* Will leave this open for the time being.
* Technology: Discord for voice, Roll20 for tabletop/video
* Variant rules: Flanking
---

If there are enough players and players can pitch a hook, we can do eet!

## Players

1. @zmoazeni / [Fenric](https://github.com/our-stories/west-marches/wiki/Character:-Fenric-Forespirit)
2. @ezcawi42 /[Frog](https://github.com/our-stories/west-marches/wiki/Character:-Frog-Hoppa)
3. @GoJustME / ?
4.

**Comment by zmoazeni** [comment]
Sorry @djigneo we'll make this happen though. I want to put together a character soon for your games

**Comment by zmoazeni** [comment]
@djigneo I'm in man! Looking forward to it!

**Comment by ezcawi42** [comment]
i'll sign up for this one

**Comment by djigneo** [comment]
You guys want to throw out a date / time slot this week or next?

**Comment by zmoazeni** [comment]
For weeknights, I'm available (all Eastern)

* Thurs Aug 20th 6pm - Midnight
* Fri Aug 21st 21st 6 - Midnight 
* Wed Aug 26th 6 - Midnight
* Thurs Aug 27th 6 - Midnight

I believe https://www.needtomeet.com/ is also free if you want to set that up. I think https://doodle.com/free-poll also has free polls, but I don't know that one off-hand.

**Comment by djigneo** [comment]
I've updated the OP to have a scheduling poll.

**Comment by GoJustME** [comment]
Voted on the poll, I can those two times, if it doesn't suit everyone else then skip me! 👍

**Comment by djigneo** [comment]
Ok. Let's nail down Aug. 28th. That'll give time for another player to join, otherwise we can roll with 3.

**Comment by djigneo** [comment]
Updated OP to have link to Roll20 campaign. Give me a token you'd like to use, or ping me when you join and I can assign you a character sheet for movement purposes.

**Comment by zmoazeni** [comment]
_While walking along the road, Fenric stops short seeing smoke in the distance and hearing a faint wailing. Gripping his quarterstaff he walks up cautiously to find a merchant wagon driven off the path, tilted precariously on a broken wheel. Arrow shafts poke out of the wood, and some remains of cargo are on fire nearby._

_On the ground he sees a gnomish merchant clinging to the motionless body of a gnomish woman, rocking and crying while holding her close. Blood stains his hands and is beginning to pool under the woman's body._

_Fenric ignores caution and runs to the merchant. He looks wounded with a nasty gash down his right calf. Taking an unused shirt from his backpack, Fenric tears it into a bandage and begins applying it to the gnome. The merchant winces but continues to cry, rocking his beloved and ignoring Fenric's aid._

_"My Tinglet. My poor poor Tinglet. I'll find her Pammy. I swear to you I will find her."_

_Fenric finishes the bandage and rocks back on his heels assessing the situation. Scanning around for any other person._

**Comment by zmoazeni** [comment]
@djigneo I updated the wiki page for Fenric to include a token https://github.com/our-stories/west-marches/wiki/Character:-Fenric-Forespirit

I came across https://2minutetabletop.com/hero-tokens-pt-2/ and generated one from that.

**Comment by djigneo** [comment]
Character sheet and Token assigned to you and Eric.

**Comment by ezcawi42** [comment]
here's a url for my token: https://cdn.discordapp.com/attachments/642953453286457357/646256773287772160/frog_topdown_finished.png

I should exist in the roll20 as well.

Also added a takeout restaurant called "The Forge" into the wiki.

_"What's the holdup!" _
_Frog had been walking down the road, sharing some Spice'Dee noodles from the Forge with his familiar, when he came upon a backup of sorts. He pushed his way to the front of the group of onlookers to find the horrible sight of some sort of attacked cart.
What looked to be a merchant was sitting on the ground, his wounds being tended to by a distinctly unassuming man. Probably an emergency responder or town doctor or something.
Frog offers his unopened second box of noodles to the merchant. _
"Hey friendo, what happened here?"

**Comment by zmoazeni** [comment]
@djigneo did we earn any XP from this? Or did we totally nope out of it? 😆

**Comment by djigneo** [comment]
**Session awards (per player):**
  **875 XP total**
  200 - Social encounters & exploration
  292 - Zombies! (x7)
  383 - Blue owl gang villa encounter

  **20 gp 6 cp total**
  20 gp - Sammy Wisecoin, for services rendered
  6 cp - from deceased bandit (1sp 7 sp split 3 ways rounded up)

**Items (party)**
1 Dagger, good condition - from deceased bandit

Up to you guys to decide what happens with dagger. Alternatively you can sell it to merchants based on PHB price (halved for selling) and split it 3 ways.

I tried to show my work. Let me know if I've missed anything.

**Comment by zmoazeni** [comment]
Gonna close this since I think this game is all wrapped up. But feel free to reopen if anyone thinks I'm too hasty.

**Comment by zmoazeni** [comment]
Oh crap I forgot we players need to post a recap. /cc @ezcawi42 @GoJustME

**Comment by zmoazeni** [comment]
_Fenric leaned back in his chair in the Sunken Hazelnut Tavern. Two empty bowls of stew sat in front of him. He scanned the patrons to see the server heading back to the kitchen to bring him a third. He had some money and tonight he would relax._

_He winced as the novice minstrel plucked yet another sour chord, but sighed contentedly. He wasn't dead. He'd likely be so if he had stormed that mansion to save that brat. Conniving her way into extorting money from her own father. Watching her step-mother slain in front of her. He hoped she enjoyed her time with those bandits. That was none of his business now._

_The bowl of soup the server was bringing him. That was his business now. And perhaps some more wine._

**Comment by ezcawi42** [comment]
my recap such as it is https://docs.google.com/document/d/1q09-_b8uGwd8OiqX_CO3owhM4GU0U3hBh8jbVhDHVzw/edit

**Comment by GoJustME** [comment]
_A seemingly onesided conversation, from any observers point of view, between Garn and his owl._
"Oi don't even bother saying that again my old friend! This has proven my point yet again... This girl faked getting kidnapped and tried to lie to and steal from her own fathe... Hey! Let me finish... Even the father turned out to be a bad man, not caring about his daughter at all besides using her as a tool for more power and money. 
No no no, he definetly didn't care about her... But back to her, she got her mother killed and still tried to use her father for money, if this doesn't prove my point what does?!? People have no good left in them. 
Yes? Huh. Well yeah maybe those two. The nice cleric man and the green one with a toad were quite nice I guess... 
But. Ye.. Well..  FINE! I'll continue doing what she wants. But you have not changed my mind yet!"
_Ënd of the conversation, as Garn and his companion returns into the woods near Waldenstone._

**Comment by GoJustME** [comment]
> 
> 
> **Session awards (per player):**
> **875 XP total**
> 200 - Social & exploration encounters
> 292 - Zombies! (x7)
> 383 - Blue owl gang villa encounter
> 
> **20 gp 6 cp total**
> 20 gp - Sammy Wisecoin, for services rendered
> 6 cp - from deceased bandit (1sp 7 sp split 3 ways rounded up)
> 
> **Items (party)**
> 1 Dagger, good condition - from deceased bandit
> 
> Up to you guys to decide what happens with dagger. Alternatively you can sell it to merchants based on PHB price (halved for selling) and split it 3 ways (3 sp 3 cp each).
> 
> I tried to show my work. Let me know if I've missed anything.

I believe that @ezcawi42 looted it so it's his to keep
