### ISSUE TITLE
Character: Heavily Falling Paw (Black Paw)

### ISSUE THREAD

**Issue by crimsonknave** [our-stories/west-marches#5]
_Please fill out your character as much as possible. Feel free to edit as much as you need. When you are all set, assign @zmoazeni to the issue._

**Name:** Heavily Falling Paw (Black Paw)

**Class** Monk

**Background:** Pirate

**Race:** Tabaxi

**Alignment:** Chaotic Evil

## Appearance:

**Age:**

**Height:**

**Weight:**

**Eyes:**

**Skin:**

**Hair:**

Description of the character that others would notice if they met them. Distinguishing tattoos, markings, mannerisms, voice.

Flesh this out as much as you can. This won't be set in stone.

## Backstory

Rough ideas: Black Paw is a surly, selfish and loyal pirate. He's quick to get into a fight if an opportunity presents itself, but will stop whatever he's doing when given an order.

## Notes

I have fleshed out the character to level 5 to get a sense of what he would look like here: https://www.dndbeyond.com/characters/18175992

**Comment by zmoazeni** [comment]
> Alignment: Chaotic Evil

@crimsonknave I don't tend to ask too much on alignment, but can you describe a couple scenarios and how Black Paw would respond to them? I am absolutely okay with Evil characters. But I also will need the party to work together.

**Comment by crimsonknave** [comment]
I've been thinking about this a bit more and I don't think Black Paw will really work in the dynamic party setting. I'd first created him for a steady pirate based campaign that never ended up happening and I really think he'd need a steady captain to keep him in line.

**Comment by zmoazeni** [comment]
Well... @crimsonknave just to be clear. Waldenstone DOES sit on the ocean. With known pirates and others. Black Paw could have gotten kicked from one of those pirate vessels. Or mutinied. 🤷 

So... maybe in time? Totally up to you. But I would love to GM and Play in high seas. ❤️
