### ISSUE TITLE
Session: Bully Whats?

### ISSUE THREAD

**Issue by zmoazeni** [our-stories/west-marches#50]
## Session information

* [Session schedule poll](https://doodle.com/poll/e6fqk6rdv5t8wmgp) - [Sun Sept 6 6-9PM Eastern](https://everytimezone.com/s/a1705a59) - [Meeting URL](https://us02web.zoom.us/j/89061103195)

## Players

1. @crimsonknave / [Quay](https://github.com/our-stories/west-marches/wiki/Character:-Quay)
2. @chrisbloom7 / [Amberscale](https://github.com/our-stories/west-marches/wiki/Character:-Amberscale-(Dragonborn-Sorcerer-3))
3. @djigneo: [Karris](https://github.com/our-stories/west-marches/wiki/Character:-Karris,-the-Namer)
4. @thyeggman / [Otru](https://github.com/our-stories/west-marches/issues/38)

GM: @zmoazeni 

## Details

* [X] **Scheduling:** Players and GMs have agreed on a time.
* [X] **Players have chosen their character and updated the session above**
* [X] **Players and GM have confirmed they have stable internet, audio, and video hardware.** (Please use a decent mic. That helps so much).
* [X] **Is this a continuation?** [Yup!](https://github.com/our-stories/west-marches/issues/34)
* [X] **GM should post a "tavern"-type RP here in the thread. To allow characters to "meet" each other via text**
* [X] **GM to share a Zoom link.**
* [X] **How deadly does the party want the session?**
* [X] **GM should post a couple of adventures for the characters to consider.**
* [X] **Has the party chosen an adventure been chosen?**
* [X] **Has the tone been chosen? laid back, silly, serious, heroic, terrifying, depressing...**
* [X] **Is the GM ready to start the game?**

**Comment by zmoazeni** [comment]
Alrighty folks! Here's the next session as a continuation of our adventure to investigate [the poor attacked fishermen](https://github.com/our-stories/west-marches/issues/34). Let me know if the dates I added to the poll don't work out.

**Comment by zmoazeni** [comment]
Looks we have a solid consensus for Sept 6th 6-9PM Eastern. That work for everyone? @crimsonknave @chrisbloom7 @djigneo @thyeggman

**Comment by zmoazeni** [comment]
I solidified the dates above. I'm also going to drop the whole recording stuff for now. Maybe we'll revive it later, but let's just have some fun for now.

Feel free to RP it up until we meeting. I'm looking forward to it!

**Comment by chrisbloom7** [comment]
Are we picking up right where we left off in the cave?

**Comment by zmoazeni** [comment]
@chrisbloom7 Yep, that's what I had in mind.

**Comment by zmoazeni** [comment]
Alrighty folks. Here's the session rewards:

* 750xp each
* 64gp each
* 3x Art objects worth ~250gp
  * Two separate boxes of turquoise figurines, one deep blue and one with black streaks through it
  * A silk robe with gold embroidery
* A wizard's spell book with 7x 1st level spells, 8x 2nd level spells, and 3x 3rd level spells. _We'll sort out the exact spells if someone wants to do something with it._
* 1x Scroll of Sleep
* 1x Scroll of Greese
* 1x Scroll of Scorching Ray

**Comment by djigneo** [comment]
Here's a calculation for selling all liquidatable items:

500 gp - Turquoise figurines
250 gp - Silk robe with gold embroidery
500 gp - Wizard's spell book *see my work below
25 gp - Scroll of Sleep
25 gp - Scroll of Grease
50 gp - Scroll of Scorching Ray

**1350 gp total** / 4 party members = 337.5 gp / share

*spell book calculation
![image](https://user-images.githubusercontent.com/15659815/92541442-a54bed00-f20b-11ea-856f-3fd7b8615e17.png)

I figure that's what we're doing, although I could see Emberscale wanting the spellbook and Karris is tempted by the robes, but hard to pass up that sort of coin.

My inclination is to sell everything. What do you guys think?

**Comment by crimsonknave** [comment]
I think we should divvy up the money and art, but keep the spell book and scrolls. Those sorts of things come in handy. We should easily have folks that can use the scrolls and maybe we'll find a use for the spellbook? I'm happy to sell the spellbook as well, if that's what folks want.

**Comment by djigneo** [comment]
@chrisbloom7 @thyeggman - thoughts?

**Comment by thyeggman** [comment]
That seems reasonable to me
