### ISSUE TITLE
Character: Garn Fleetfoot

### ISSUE THREAD

**Issue by GoJustME** [our-stories/west-marches#54]
_Please fill out your character as much as possible. Feel free to edit as much as you need. When you are all set, assign @zmoazeni to the issue._

**Name:** Garn Fleetfoot

* Race (and subraces if any): Lightfoot Halfling
* Class(es) w/Levels: Warlock 3
* Alignment: Neutral Good 

**Character sheet:** https://www.dndbeyond.com/profile/GoJustME/characters/33953562

## Appearance:

A short, tanned and rough looking halfling male donning a big smile. Wandering barefoot with torn, too short brown pants, a matching shirt that's filled up with his round belly, and a thinner, light green cloak. He has long, lightbrown hair with the occasional vibrant green leaf in it. He has a matching bushy beard that's unmanaged. His eyes are a deep forest green that are almost blocked by his bushy eyebrows. He is carrying a quarterstaff with a matt green stone set slightly above the leather wrappings where he holds the staff.

**Age:** 48

**Height:** 3'

**Weight:** 42 lb.

**Eyes:** Forest green

**Skin:** Tanned, rough skin

**Hair:** Long, Light brown

## Backstory

Garn Fleetfoot was born into a humble family in a small halfling village. His parents worked as livestock farmers, keeping various animals. Growing up, Garn was a social people person always running around being a part of everyones buisness. But as he grew older he got a taste of the worlds unjustices and the greed of the people around him. He grew tired of never being able to trust anyone, so he left the towns and villages to live a life in the woods.

Garn continued living his life in isolation from other people. With noone but the animals of the forest as his company. But something was not right. Garn was having strange dreams and visions, visions of a strange, bright glowing creature. The experience filled Garn with a strange feeling that he hadn't felt in years, the urge to help. As timed passed Garn started to uncover new powers he hadn't possessed before, and the feeling of having to help others grew. So he left his forest home, set out to once again walk among the people of Exandria.

## Potential Plot Hooks

Garn struggles to see the good in people, but are urged by his patron to help others. It is an internal struggle that is constantly ongoing within him. It is the agreement between Garn and his patron, to always try to help people in need. Failure to do so could lead to the patron not granting it's favor to Garn.

**Comment by zmoazeni** [comment]
@GoJustME I love it! Wow. Really excited to see Garn in action!

Could you spin up a wiki page and push this info over there? 🙏 

Feel free to spin up any new session threads or join existing ones. And welcome!

**Comment by zmoazeni** [comment]
All set https://github.com/our-stories/west-marches/wiki/Character:-Garn
