### ISSUE TITLE
Character: Lucius 

### ISSUE THREAD

**Issue by DixieBryan** [our-stories/west-marches#56]
https://ddb.ac/characters/33891838/GDYKWg

**Comment by zmoazeni** [comment]
@DixieBryan skimming the character sheet, it looks pretty good. When you make a Wiki page though can you fill out more information on Lucias's background and description? Thanks!

**Comment by chrisbloom7** [comment]
Cool! TIL about [Ravenite Dragonborn](https://www.nerdsandscoundrels.com/ravenite-dragonborn-5e/)

**Comment by zmoazeni** [comment]
@DixieBryan I'm sorry for the whiplash in communication. Can you instead create a thread on https://ourstories.connectionrequired.com/c/characters/6? We are no longer going to use GitHub to manage characters
