### ISSUE TITLE
Character: Harah

### ISSUE THREAD

**Issue by RedPandaPaladin** [our-stories/west-marches#58]
_Please fill out your character as much as possible. Feel free to edit as much as you need. When you are all set, assign @zmoazeni to the issue._

**Name:** Harah

* Race (and subraces if any): Warforged
* Class(es) w/Levels: Paladin 3
* Alignment: Neutral Good

**Character sheet:** https://ddb.ac/characters/33487661/l14lem

## Appearance: Harah often is hunched over and wears a ragged green cloak with an insignia of two crossed hammers on it. His body looks frail and made of copper and brass, but the way the materials are interwoven make it much stronger than it looks.. His face is a clock. He can still see and speak, but his eyes and mouth are not visible.. He speaks in a deep and gravelly voice, with a slight Southern accent.

**Age:** 50

**Height:** 6"

**Weight:** 220

**Eyes:** None

**Skin:** Copper and brass

**Hair:** None

**Comment by zmoazeni** [comment]
Fantastic. 

![](https://media.tenor.com/images/e4b1767e1d07d25bcd6d61fc5fddd3a1/tenor.gif)

Can you toss Harah in the wiki?

**Comment by zmoazeni** [comment]
@RedPandaPaladin I meant something like this https://github.com/our-stories/west-marches/wiki/Character:-Frog-Hoppa

**Comment by zmoazeni** [comment]
@RedPandaPaladin I'm sorry for the whiplash in communication. Can you instead create a thread on https://ourstories.connectionrequired.com/c/characters/6? We are no longer going to use GitHub to manage characters
