### ISSUE TITLE
Character: Raven's Caw

### ISSUE THREAD

**Issue by crimsonknave** [our-stories/west-marches#6]
_Please fill out your character as much as possible. Feel free to edit as much as you need. When you are all set, assign @zmoazeni to the issue._

**Name:** e.g. Raven's Caw

If you need help with generating a name: https://www.fantasynamegenerators.com/dungeons-and-dragons.php

**Class** Rogue

**Background:** Soldier

**Race:** Kenku

**Alignment:** Chaotic Neutral

## Appearance:

**Age:**

**Height:**

**Weight:**

**Eyes:**

**Skin:**

**Hair:**

Description of the character that others would notice if they met them. Distinguishing tattoos, markings, mannerisms, voice.

Flesh this out as much as you can. This won't be set in stone.

## Backstory

Your character wasn't born yesterday. Where did they come from? What have they struggled with in the past?

Even though other players can read your character's background, their characters won't act on it unless it is shared with them in game.

## Note

I have fleshed out the character to level 5 to get a feel here: https://www.dndbeyond.com/characters/28705755

**Comment by zmoazeni** [comment]
> Chaotic Neutral

@crimsonknave I'm going to ask the same as I did with Black Paw. Can you describe a couple scenarios and how Raven's Caw would react to them? Chaotic Neutral is one of those that can be "I do what I want!" sort of characters. I would like to avoid that a little.

**Comment by crimsonknave** [comment]
Closing for now as I plan on playing Quay. Will open a new issue if want to play a different character.
