### ISSUE TITLE
Character: Zemo Featherbottom

### ISSUE THREAD

**Issue by DanielOhn** [our-stories/west-marches#60]
**Name:** Zemo Featherbottom

* Race (and subraces if any): Lightfoot Halfling
* Class(es) w/Levels: Rogue, Level 1
* Alignment: Neutral Good

**[Character Sheet](https://ddb.ac/characters/34233298/nTmy5K)**

## Appearance:
**Age:** 25

**Height:**  2’7

**Weight:** 37 lbs.

**Eyes:** Green

**Skin:** Beige

**Hair:** Almond Brown

Zemo Featherbottom is a two feet and seven inch tall lightfoot halfling with beige hue for his skin.  He has short hair that is almond brown with distinctive, green eyes.  Around his neck he wears a sage green bandana which matches his green colored tunic with dark khaki pants. Over his tunic he usually wears brown leather armor and tends to walk about barefooted with his hairy feet. 

## Backstory
Zemo is a halfling that is a commoner, most of his life he has been working on the land and hunted for his small village to provide food, along with assembling and disassembling various traps to help catch prey.

One day he stumbled upon a group of goblins and discovered by a group who assumed he killed them all, after he was praised as a folk hero and enjoyed the feeling of being praised which made him go out and become an adventurer. 

His goal as an adventurer is to make the land safer for the common person and making it a better place for everyone.

The main niche that Zemo fills in a party is providing the ability to use thieves' tools to disarm traps, open locked chests, pretty good at traveling in the wilderness from hunting, and is a ranged DPS.

- Exploration
 Zemo is a natural explorer, preferring more natural landscapes such as forests and grasslands, but should do well in any type of setting.

- Social
Zemo is pretty charming and well liked.  He can relate to the common person since he is a commoner himself, but tends to try too hard and make himself seem more important and smarter than he actually is.  He is a pretty confident individual and tries to see the best in each person, and make them become the best version of themselves. 

- Combat
Zemo is a rogue and uses a short bow to deal damage.  He’ll take advantage of sneak attack by attacking enemies who the front-line is tanking or attempting to focus, along with being a lightfoot halfling he could easily hide away in the distance from enemies.

- Proficiency
My main goal with Zemo is to have him be able to deal good damage from a distance, be sneaky occasionally like most rogues, help navigate through the wilderness, and disarm traps and chests. He is also proficient in leather working so he might skin animals or beasts that the party slays and will attempt to utilize them in some way.

## Potential Plot Hooks
Of course, Zemo is not without flaw.  He tends to be overconfident in his abilities and thinks highly of himself, if any lies come up that paints him in a good light he would definitely confirm it as the truth, and when it comes to the bottle it tends to be a big weakness of the halfling.

**Comment by chrisbloom7** [comment]
I love the name!

**Comment by zmoazeni** [comment]
Closing with https://ourstories.connectionrequired.com/t/zemo-featherbottom/15/2
