### ISSUE TITLE
Character: Orsik Karsrak

### ISSUE THREAD

**Issue by crimsonknave** [our-stories/west-marches#7]
_Please fill out your character as much as possible. Feel free to edit as much as you need. When you are all set, assign @zmoazeni to the issue._

**Name:** Orsik Karsrak

**Class** Cleric

**Background:** Guild Artisan

**Race:** Hill Dwarf

**Alignment:**

## Appearance:

**Age:**

**Height:**

**Weight:**

**Eyes:**

**Skin:**

**Hair:**

Description of the character that others would notice if they met them. Distinguishing tattoos, markings, mannerisms, voice.

Flesh this out as much as you can. This won't be set in stone.

## Backstory

Roughly Orsik grew up in a dwarven crafting community and has worked for decades to perfect his art. He now travels to learn new things, share his work with the world and get recognition for his skills.

## Notes

I have fleshed the character out to level 5 to get a feel: https://www.dndbeyond.com/characters/28803327

**Comment by zmoazeni** [comment]
😍 I love me some dwarven clerics. Or dwarves in general. Can you flesh out a little more of a description for other players? Thanks!

**Comment by crimsonknave** [comment]
Closing for now as I plan on playing Quay. Will open a new issue if want to play a different character.
